// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClassFilterController from "./class_filter_controller"
application.register("class-filter", ClassFilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import StatPointsController from "./stat_points_controller"
application.register("stat-points", StatPointsController)

import BattleMsgController from "./battle_msg_controller"
application.register("battle-msg", BattleMsgController)
